### ISSUE TITLE
Implement new Styleguide

### ISSUE THREAD

**Issue by deepflame** [itsinthenode/styleguide#3]
The new styleguide can be found here:
https://www.figma.com/file/S39H0B1LOnaVICIUiApFTfoP/_Style-Guide-Desktop-Style-Guide

If one creates an account it is also possible to copy CSS and stuff.

Good luck!

**Comment by tarikEast** [comment]
Seems like forms-for that you have suggested for forms have a lot of issues and it's not maintained. I have found couple of workarounds for some issues, but the main issue that I managed to find and have no solution is on validation with ember-changeset and ember-changeset-validations plugin. I made an example [here](https://github.com/tarikEast/ember-forms)

**Comment by tarikEast** [comment]
I'll make css changes in stylesheet as we were to use form-for, it can be changed to match other styles

**Comment by jf1978** [comment]
we have a ticket for this in the issues list, replace with that? /itsinthenode/issues/issues/1957

**Comment by deepflame** [comment]
@jf1978 as Tarik pointed out in Slack this issue is part of the overall styleguide transition. This is to implement the Sketch file in CSS. Then the CSS needs to be applied to components which need to be used in the app. It is a multi step process.
So I would leave this here.

@tarikEast `ember-form-for` does not seem unmaintained to me but maybe you think because of the many open issues? You can try to find a better alternative here: https://emberobserver.com/
or we may even start our own library or use one and extend it to our liking.

**Comment by jf1978** [comment]
@deepflame thanks for clarifying, will update itsinthenode/issues#1957 with a more clear headline according to your description here.

**Comment by jf1978** [comment]
I added label question for @deepflame question to @tarikEast

**Comment by deepflame** [comment]
Ok, guess I see what you mean Tarik. The current maintainer of the addon is looking for a new one for different reasons. See here: https://github.com/martndemus/ember-form-for/issues/ 179 (did not want to autolink :) )

**Comment by deepflame** [comment]
Tarik prepared a pull request here: https://github.com/itsinthenode/styleguide/pull/4

**Comment by mathorn** [comment]
i started implementing the new styleguide for desktop

**Comment by mathorn** [comment]
Hej @deepflame and @tarikEast , had a look at different form addons and validations, would tend to use ember-form-for with ember-changeset and ember-changeset-cp-validations . As it seems form-for will be probably merged with ember-do-forms (which would be my second choice), so I think we are ok with using it for now. Any objections?

**Comment by tarikEast** [comment]
@mathorn I found an issue with ember-for and ember-changeset, and I am not sure if it's my lack of knowledge on plugins or it's an issue with the plugin itself. Here is an example https://github.com/tarikEast/ember-forms (if you need access to the repo please let me know). Issue is following: when form-for has more than one validation error it stays in error state. Would need to look into the example to give you exact steps.

**Comment by jf1978** [comment]
@tarikEast what is status on this issue. Can it be closed?

**Comment by tarikEast** [comment]
@jf1978 closing it due it's implemented on style-guide for what is common on apps
